/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProject: typeof import('./src/components/addProject/index.vue')['default']
    Arrowhead: typeof import('./src/components/title/arrowhead.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    DbTableHeader: typeof import('./src/components/dbTableHeader.vue')['default']
    Diamond: typeof import('./src/components/title/diamond.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconTitle: typeof import('./src/components/iconTitle.vue')['default']
    IndexMap: typeof import('./src/components/relationMap/indexMap.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Lists: typeof import('./src/components/lists/index.vue')['default']
    Map: typeof import('./src/components/map/components/Map.vue')['default']
    MaxMap: typeof import('./src/components/mapView/maxMap.vue')['default']
    MinMap: typeof import('./src/components/mapView/minMap.vue')['default']
    ProjectChildModule: typeof import('./src/components/addProject/projectChildModule.vue')['default']
    ProjectModule: typeof import('./src/components/addProject/projectModule.vue')['default']
    RelationMap: typeof import('./src/components/relationMap/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondTile: typeof import('./src/components/title/secondTile.vue')['default']
    Title: typeof import('./src/components/title/index.vue')['default']
    ZbList: typeof import('./src/components/lists/zbList.vue')['default']
    ZbList2: typeof import('./src/components/lists/zbList2.vue')['default']
  }
}
